return {
	infiniteLoop = 'Detected an infinite loop. Consider adding an explicit breakpoint to your code to prevent a cyclic dependency.',
	callbackError = 'Error in callback:\nERROR_MESSAGE',

	invalidObserveType = "Can't observe non-state value, got '%s'.",

	propertyInvalidType = "'%s.%s' expected a '%s' type, but got a '%s' type.",
	propertyCannotAssign = "The class type '%s' has no assignable property '%s'.",
	propertyAssignError = 'Error while setting property:\nERROR_MESSAGE',

	cannotDepend = '%s cannot depend on %s.',
}
